= Scripts for extracting Core Keeper data

== Data extraction

=== Requirements

* Python 3.8+
* Python venv
* https://github.com/AssetRipper/AssetRipper[AssetRipper]

Before extracting any data, `venv` needs to be initialized and the needed `pip-packages` needs to be installed.

.Init venv and install pip packages
[source,bash]
----
python3 -m venv ./venv
pip install -r requirements.txt
----

To extract the assets we need to be on Windows (`AssetRipper` is cross-platform but does not extract everything on linux)
Open `AssetRipper`, File > Open Folder > Core Keeper Folder.
The Core Keeper folder is by default located at `C:\Program Files (x86)\Steam\steamapps\common\Core Keeper`.
Export > Export all Files into the `/dump` folder. This can be done in 2 steps if you execute this program in linux.

Now you can execute:

[source,bash]
----
./items.py && ./conditions.py && ./talents.py
----

The extracted data should be in `/out`.

To override the old data in the projects do:

[source,bash]
----
./deploy.py
----

=== How it works

To get reliably all the items we have chosen to use the `PugDatabase` file as the starting point.
Based on the database we filter out the object we definetly know we don't need. This includes filter by object type and a blacklist which we tested.
After that we export all the needed information and icons.


== How to handle Core Keeper updates

=== Skill balancing:

When they rebalance, use https://www.cheatengine.org/[Cheat Engine] to extract the constants:

* Open `Cheat Engine` and select `Core Keeper`
* Select Mono > .Net Info (Ctrl + Alt + N) on the toolbar
* Select Pug.Other.dll on the left side
* Select SkillData in the middle
* Read the MulFactor and Base variables for all the skills and change it in our link:../src/app/services/skill-talent.service.ts[SkillTalentSerivce]

=== Conditions which are off of a factor of 10

There is a small logic when displaying conditions where certain skills needs to be divided by 10:

* Use https://github.com/Perfare/Il2CppDumper[Il2CppDumper] and dump the code
* This will generate a `DummyDll`. Open that folder with https://github.com/dnSpy/dnSpy[DnSpy].
* Find `Condition` in `Pug.Other` and find and copy the `VA` for `public static string GetConditionValueString(ConditionEffect effect, int value, bool showPlusSign)`
* Use https://github.com/NationalSecurityAgency/ghidra[Ghidra] and open `GameAssembly.dll`
* Start analysing and go to the `VA` address with `Ctrl + G`
* Extract the if condition and adjust the current one in link:./conditions.py[conditions.py]

=== Items.py Warning

Certrain objects don't have `icons` or `translations` (not real items). We log these when extracting data. This helps us to identifiy false exclusion of the data. But when we are sure that these `objectIDs` are in fact not items we add them to our link:./blacklist.py[blacklist.py].