= Scripts for extracting Core Keeper data

== Data extraction

=== Requirements

* Python 3.8+
* Python venv
* https://github.com/AssetRipper/AssetRipper[AssetRipper]

Before extracting any data, `venv` needs to be initialized and the needed `pip-packages` needs to be installed.

.Init venv and install pip packages
[source,bash]
----
python3 -m venv ./venv
pip install -r requirements.txt
----

To extract the assets we need to be on Windows (`AssetRipper` is cross-platform but does not extract everything on linux)
Open `AssetRipper`, File > Open Folder > Core Keeper Folder.
The Core Keeper folder is by default located at `C:\Program Files (x86)\Steam\steamapps\common\Core Keeper`.
Export > Export all Files into the `/dump` folder. This can be done in 2 steps if you execute this program in linux.

Now you can execute:

[source,bash]
----
./items.py && ./conditions.py && ./talents.py
----

The extracted data should be in `/out`.

To override the old data in the projects do:

[source,bash]
----
./deploy.py
----

=== How it works

To get reliably all the items we have chosen to use the `PugDatabase` file as the starting point.
Based on the database we filter out the object we definetly know we don't need. This includes filter by object type and a blacklist which we tested.
After that we export all the needed information and icons.
